### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/nazareth-recipes#27]
We want some rights for when this blows up

**Comment by finnhodgkin** [comment]
I'd go for [GPL v.2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html)

> We protect your rights with two steps: (1) copyright the software, and (2) offer you this license which gives you legal permission to copy, distribute and/or modify the software.
Also, for each author's protection and ours, we want to make certain that everyone understands that there is no warranty for this free software. If the software is modified by someone else and passed on, we want its recipients to know that what they have is not the original, so that any problems introduced by others will not reflect on the original authors' reputations.
Finally, any free program is threatened constantly by software patents. We wish to avoid the danger that redistributors of a free program will individually obtain patent licenses, in effect making the program proprietary. To prevent this, we have made it clear that any patent must be licensed for everyone's free use or not licensed at all.

GPL 2.0 would prohibit large corporations (Jamie Oliver, etc.) from patenting the recipes, while also maintaining the open sauce communities' right to play and edit.

**Comment by m4v15** [comment]
Why 2.0 and not 3.0

**Comment by finnhodgkin** [comment]
No reason except that we use it at dwyl. 

Having googled I see no reason not to use v3 - it's pretty much the same except it's more legally robust.
