### ISSUE TITLE
Bam! Mavis Peter Davis.

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/nazareth-recipes#53]
Stop editing my comments mate

**Comment by m4v15** [comment]
No @Karyum, it's ok, we can forgive you. ❤️

**Comment by Karyum** [comment]
@m4v15 
# @ssH0le!!

**Comment by m4v15** [comment]
I think you need to calm down Mario. Sleep on it.

**Comment by finnhodgkin** [comment]
I think we need a mood monitor in here.

**Comment by Karyum** [comment]
@m4v15 nah mate it's going to be a full on war if my pr does not get merged. 
I also want to say that @finnhodgkin and @matthewdking were laughing at this pr (Arabic omelette) and not taking it seriously cause it has the word Arabic in it (*which is racist btw and does not go with our FAC values*)

also @m4v15 why did you not revert king's PR ? when Yvonne merged and you were not okay with it ? the way i see it right now just cause you might know me well and have lived in the same place for like 8 months  you feel like you are privileged to revert my PR, that is discrimination at it's finest and im not having it mate. 

**You guys have crossed the line here**

**Comment by m4v15** [comment]
You can't stop people laughing at things Mario, I'm sorry.

You are correct, when Yvonne did it I didn't revert it, but that was because it was my own review that was being waited for, and also it wasn't in the contributing guide at the time she did it. If you knew it was frowned upon from that, why did you do it yourself? 

Feels like you're backed into a corner and making excuses mate, just admit you were wrong to merge your own PR and move on 🇬🇦  🇺🇬

**Comment by m4v15** [comment]
I think you're taking it too personally as well, it's not about you, it's about the integrity of Nazareth Recipes, I think that's reflected in me backing you up multiple times on the PR.

**Comment by Karyum** [comment]
@m4v15 i did not revert it cause i trusted in your decision as a maintainer now not so much, I'm not backed into a corner you are just taking a piss at this (*reverting my pr*) cause there wasn''t a valid reason behind it

**Comment by Karyum** [comment]
@m4v15 if it's about the "integrity" why did you merge your own PR when reverting ? i think it should have been discussed mate **Don't speak to me about integrity**

**Comment by m4v15** [comment]
Hmmm you're maybe right about that, but I think the rules probably slightly change when reverting a previous mistake. Maybe I did overstep the line in correcting your original mistake.

**Comment by Karyum** [comment]
@m4v15 also i bet i can find other pull requests in which we skipped over people who requested changes

**Comment by m4v15** [comment]
tbh the bigger issue is your merging your own PR 🆘  ⚗️ 🐨

**Comment by Karyum** [comment]
@m4v15 that's not your issue mate. your issue is apologizing (*with a Z mate cause whatsup?*)

**Comment by m4v15** [comment]
Nah, it's about merging your own PR, I'm pretty sure. Or are you asking me to apologise? Sure. I'm sorry that you didn't learn on the course that you shouldn't merge you own PRs.

**Comment by m4v15** [comment]
Ok actually, this has all got out off hand, and is unbecoming of us as maintainers and the Nazareth Recipe's repo.

I apologise to everyone involved, I overstepped the line, thinking I was doing what was right. Can we end this here (or at least just leave all the comments about to this one issue) 😫 

I revert the revert, but fear that will lead to more accusations of overstepping the line, so will leave it as it is ❤️

**Comment by finnhodgkin** [comment]
In my opinion the language and tone of this issue is inappropriate for NazRec (do we need a code of conduct?) and should be closed. I'm sure @Karyum doesn't really want to ban @m4v15 and that he didn't really mean it when he accused King and me of racism.

>I also want to say that @finnhodgkin and @matthewdking were laughing at this pr (Arabic omelette) and not taking it seriously cause it has the word Arabic in it (which is racist btw and does not go with our FAC values)

To quickly address that point, there's a misconception here: the King and I weren't laughing at the fact the recipe has the word Arabic in it, we were laughing at @Karyum's lack of evidence that the recipe is specifically Arabic. To our uneducated eyes it was just a standard international omelette with some green onions and a bit of za'atar. @shiryz has since supplied us with more context and I'm willing to wholeheartedly apologise and merge the recipe with the current title, though we should definitely leave room for @shiryz's own version as [stated here](https://github.com/foundersandcoders/nazareth-recipes/pull/54#issuecomment-342293354).

Let's try to keep the discussion jolly from now, the world is watching us :heart:
